version: '3.8'

services:
  texsvc:
    container_name: fomtextemplate
    image: fomtextemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/fomtextemplate:rw